### ISSUE TITLE
Unexpected token in JSON

### ISSUE THREAD

**Issue by hanxue** [nathanbuchar/electron-settings#104]
I get JSON parsing error when using `.has()` or `.getAll()`

```
Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (build.js:42054)
    at __webpack_require__ (build.js:20)
    at build.js:63
    at build.js:66
```

The settings file is entirely created by `electron-settings`. I have made sure of this by deleting the `app.getPath()/AppName/Settings` file. 

My app initialisation code has this

```js
var questSettings = {
  questBackend: {
    port: "2222",
    host: "192.168.1.17"},
  websocketBackend: {
    host: "192.168.1.17",
    port: "3333"}
}
if (settings.has('questBackend.host')) {
  questSettings = JSON.parse(settings.getAll())
}
```

This is the JSON Settings file content
```json
{"questBackend":{"host":"192.168.1.17","port":"2222"},"websocketBackend":{"host":"192.168.1.17","port":"3333"}}
```

Writing settings has no problem, for example `settings.set('questBackend.port', value)`

**Comment by nathanbuchar** [comment]
Likely a result of #81. Are you running electron-settings in the server and renderer process?

**Comment by nathanbuchar** [comment]
Closing this as it pertains to an older version of Electron Settings. A new major release (v4) of Electron Settings was just released!
