### ISSUE TITLE
More lenient peerDependencies?

### ISSUE THREAD

**Issue by theflow** [nathanbuchar/electron-settings#11]
Was trying to upgrade to the newest electron release (0.37.5) and got this:

```
npm ERR! peerinvalid The package electron-prebuilt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer electron-settings@1.0.3 wants electron-prebuilt@^0.36.0
```

would it make sense to allow a greater range of versions?

**Comment by nathanbuchar** [comment]
You're right, this was an oversight. In fact I'll remove the peer dependency altogether, it feels a bit redundant

Thanks for flagging :)
