### ISSUE TITLE
After new install, users get ENOENT: No Such File on /Users/user/Library/Application Support/appname/Settings

### ISSUE THREAD

**Issue by kkitay** [nathanbuchar/electron-settings#111]
<img width="532" alt="screen shot 2018-11-14 at 9 20 11 am" src="https://user-images.githubusercontent.com/1082318/48489243-999a6580-e7f0-11e8-9270-b5b99c57cf02.png">

one users had Mac OS 10.10 and I'm finding out about the other. This only happens to users installing for the first time. I feel like this is an electron-settings bug, and needs to create the directory before trying to save.

My repo is here: https://github.com/kkitay/raccoon/

**Comment by kkitay** [comment]
I found that this issue https://github.com/nathanbuchar/electron-settings/issues/84 had the answer to my problem: I was requiring a file that required electron-settings outside of the `app.on('ready')` callback. After moving it all in, things are working fine.

**Comment by nathanbuchar** [comment]
Glad to hear you figured it out :)
