### ISSUE TITLE
time delay in .get() ?

### ISSUE THREAD

**Issue by mbykov** [nathanbuchar/electron-settings#113]
.get() does not work for me. 

let state = settings.get('state')
log('STATE', state)
gives {}, 

end when I click on it, shows correct values. But

log('FOO', state.foo) gives undefined, and
let foo = settings.get('state.foo') gives undefined

Linux, Electron 4.1.1, "electron-settings": "^3.2.0"

**Comment by nathanbuchar** [comment]
Electron Settings is synchronous, so there shouldn't be any race conditions here. Can you run the following for me and tell me the output?

```js
console.log(settings.get('_test'));
settings.set('_test', { foo: 'bar' });
console.log(settings.get('_test'));
settings.delete('_test');
console.log(settings.get('_test'));
```

Thanks :)

**Comment by nathanbuchar** [comment]
Oh I see, you're accessing `state` as if it were dynamic. The value of `state` will NOT change if you update settings via `settings.set()`. It's not an internal cache, it reads it from the settings file on disk. If you update the settings, you need to do `settings.get()`.

**Comment by mbykov** [comment]
But how I should do set, then get? 

  console.log('get_test',settings.get('_test'));
  settings.set('_test', { foo: 'bar' });
  console.log('get_test', settings.get('_test'));
  console.log('get_test2', settings.get('_test'));
  settings.delete('_test');
  console.log('get_test', settings.get('_test'));

Now I've got, I already click on second {}  - see picture also

get_test undefined 
get_test {}
get_test2 {}foo: (...)get foo: () => {…}set foo: (value) => {…}__proto__: Object
get_test undefined
![set_get](https://user-images.githubusercontent.com/47331/56077304-40f0e800-5de3-11e9-9b0f-557da704180a.png)

**Comment by mbykov** [comment]
Oh, I see. I can not use E.S. as internal cache at all, only after restart. Well, ok, thank you!
