### ISSUE TITLE
Possible Bug? Or perhaps I am misusing

### ISSUE THREAD

**Issue by wilburforce83** [nathanbuchar/electron-settings#114]
Hi There, I'm not sure if this is a bug, or just something I am messing up.

If I set an object in an array that has other objects, it over-writes the whole array:

```
settings.set('example', {

item1: 10, 
item2: 20,
item3: 30
})
```

If I then want to change `item1` independently from the others:

```
settings.set('example', {

item1: 25
})
```

The array now reads: `{"example":{"item1":25}}` 

I.e. it has literally set the array as per my request, rather than ignored `item2 ` and `item3`. I have resolved this by naming independent settings as:

```
settings.set('item1', {

item1: 10
})
settings.set('item2', {

item2: 20
})
settings.set('item3', {

item3: 30
})
```

so I retrieve my data with settings.get('item1.item1') and so on.

I this the correct usage or am I missing a simple settings.edit / ammend call?

Many thanks!!

Will

**Comment by nathanbuchar** [comment]
Electron settings won't merge. If you set a property, the value you provide will be the new value, it won't be merged with the existing value.

Here's how you update `item1` while preserving `item2` and `item3`. Use keypaths! :)

```js
settings.set('example', {
  item1: 10, 
  item2: 20,
  item3: 30
});
```

```js
settings.set('example.item1', 25);
```

**Comment by nathanbuchar** [comment]
Feel free to re-open if this doesn't solve your issue

**Comment by wilburforce83** [comment]
Ah perfect! Thank you so much. I am sure you can tell, but I am quite new
to JS and this has helped me no end!
