### ISSUE TITLE
Exception while reading setting on fresh system first time

### ISSUE THREAD

**Issue by pashvin** [nathanbuchar/electron-settings#116]
I have code to read setting on startup
line 25: let lang = settings.get('lang') ? settings.get('lang') : navigatorLang;
For fresh machine , when I start app first time , I see exception.
Second time I start app and everything is fine.

I am using Electron 4.x and electron-settings 3.2.0

![image](https://user-images.githubusercontent.com/36708072/58272921-71ae3080-7d44-11e9-9e5c-9b0c056c8853.png)

**Comment by ramaralo** [comment]
I'm having the same issue. MAC and WIN.

@pashvin Did you get to any conclusion/workaround meanwhile?

**Comment by ramaralo** [comment]
To reproduce, just delete the app dir that contains the `Settings` file.

Run the app again, and the error occurs.

**Comment by pashvin** [comment]
I just added try catch on the first call of this npm module.

**Comment by ramaralo** [comment]
Well, are you calling the settings module before the `app.ready` event?
If so, that may be the cause.

It was on my case. The settings assumes the app folder is created by the time you call it. And folder isn't created until `app.ready` event is fired. 

`app.on('ready', () => {
// call settings here
})`

So this is not a `settings` issue for me.

Thanks.

**Comment by pashvin** [comment]
Yes my code is called after app read but try catch workaround works for me.
