### ISSUE TITLE
`content.replace is not a function ` inside renderer script

### ISSUE THREAD

**Issue by mubaidr** [nathanbuchar/electron-settings#119]
I get following error trying to use this library in the renderer process. 

```bash
settings.js?3b5d:199 Uncaught TypeError: C:\Users\minion\AppData\Roaming\Electron\Settings: content.replace is not a function
    at stripBom (index.js?c313:123)
    at Object.readFileSync (index.js?c313:62)
    at Settings._readSettings (settings.js?3b5d:195)
    at Settings._getValueAtKeyPath (settings.js?3b5d:281)
    at Settings.get (settings.js?3b5d:404)
    at new Cache (Cache.ts?7517:10)
    at eval (cache.ts?cb0b:3)
    at Module../src/utilities/cache.ts (renderer.js:7914)
    at __webpack_require__ (renderer.js:728)
    at fn (renderer.js:102)
```

System & version information: 
![Capture](https://user-images.githubusercontent.com/2222702/61852526-8c00a980-ae6e-11e9-85e8-a5d1f6845abd.PNG)

Any idea what could be wrong?

**Comment by nathanbuchar** [comment]
I use `jsonfile` to read the settings file and parse it as JSON. It looks like it fails on this line:

https://github.com/jprichardson/node-jsonfile/blob/master/index.js#L126

Can you look at your settings file (`C:\Users\minion\AppData\Roaming\Electron\Settings`) and confirm that it's not corrupted and encoded correctly (UTF8)? Does it look like regular JSON?

**Comment by mubaidr** [comment]
It has `{} ` as content, which is fine i guess since no settings have been saved yet.

**Comment by nathanbuchar** [comment]
Yeah that's perfectly valid. Strange, I haven't seen this issue come up before. Can you delete the `Settings` file and let the framework generate a new one in case for whatever reason that file is corrupted in some way?
