### ISSUE TITLE
electron-settings not found

### ISSUE THREAD

**Issue by Dahkenangnon** [nathanbuchar/electron-settings#123]
I'm coding an electron app with Vue-Cli Electron builder from here :   https://nklayman.github.io/vue-cli-plugin-electron-builder/

I'd install electron-settings but when i build the production version of the app it can't run properly due to an error with this error:

`Uncaught Error: Cannot find module 'electron-settings'
`

I use `"electron-settings": "^3.2.0",`

Thank for any idea to fix it

**Comment by jasonraimondi** [comment]
@Dahkenangnon Make sure you included electron-settings in the "dependencies" section of your `package.json` file, **NOT the devDependencies**.

**Comment by Dahkenangnon** [comment]
Oh yes, thank you.
it works now after i moved "electron-settings" under "dependencies".

Thank you very much @jasonraimondi

**Comment by jasonraimondi** [comment]
Glad I was able to help, cheers!
