### ISSUE TITLE
Values clear on app start (Mac OS Yosemite)

### ISSUE THREAD

**Issue by camhart** [nathanbuchar/electron-settings#124]
I'm testing my app on Mac OS Yosemite, and it appears the values all get cleared each time the app starts.  No errors thrown or anything, the file just gets shrunk down to {} no matter what.

**Comment by nathanbuchar** [comment]
Closing this as it pertains to an older version of Electron Settings. A new major release (v4) of Electron Settings was just released!

**Comment by roggenbrot** [comment]
This happens to me also when using 4.0.2 when packaging the app with electron-builder as AppImage. 

On each start the values in the file get cleared. 

This happens only when bundled with electron-builder.
