### ISSUE TITLE
App update

### ISSUE THREAD

**Issue by Ishaangandhi** [nathanbuchar/electron-settings#125]
How are settings saved? If an app is updated via (electron-updater)[https://www.npmjs.com/package/electron-updater], will electron-settings still have access to the settings?

**Comment by nathanbuchar** [comment]
Hi @Ishaangandhi! The settings are saved in the app's user data directory on the user's machine. For macOS, this would be something like `~/Library/Application\ Support/<Your App>`. If you app is pushed an update, the settings will persist :)
