### ISSUE TITLE
update npm repository with version 4.0.0 !

### ISSUE THREAD

**Issue by AlbanMinassian** [nathanbuchar/electron-settings#127]
today 2020-06-05 ``npm install electron-settings`` => electron-settings@3.2.0
expect electron-settings@4.0.0

Have you plan to upate npm registry ?

Thank

**Comment by AlbanMinassian** [comment]
``https://github.com/nathanbuchar/electron-settings`` install empty directory !!!

**Comment by nathanbuchar** [comment]
Hey @AlbanMinassian, I was just waiting a few days in case there was anything I wanted to change before publishing. v4 was just published!

**Comment by AlbanMinassian** [comment]
Thank you
