### ISSUE TITLE
Peer Dependency Electron

### ISSUE THREAD

**Issue by travisjames** [nathanbuchar/electron-settings#128]
After update to v4, npm keeps throwing the following error, even with electron installed:

> "electron-settings@4.0.0 requires a peer of electron@^2.0.0 but none is installed. You must install peer dependencies yourself."

**Comment by nathanbuchar** [comment]
Whoops, I was accidentally too explicit with the version. I should have used `">= 3"`. I'll fix this later today. Sorry bout that, and thank you so much for flagging!
