### ISSUE TITLE
Why delete watch method on new version

### ISSUE THREAD

**Issue by fatoldsun00** [nathanbuchar/electron-settings#139]
Hi,

I analyse an electron app who use 3.2 of electron-settings. I see in code use of 2 methods : watch and emit.
Correct me if i wrong, this methods are not part of the new version :  class doesn't extends of eventEmitter and watch has disappeared.

Why ? perf killer ? 

Thank you for your work !

**Comment by Arjan-Zuidema** [comment]
We still use an older version because of the removal of the `watch` feature.

**Comment by fatoldsun00** [comment]
> 
> 
> We still use an older version because of the removal of the `watch` feature.

**Comment by nathanbuchar** [comment]
Hi @fatoldsun00, check out the _Reducing Complexity_ part of my [blog post](https://nathanbuchar.com/electron-settings-v4/). I'd like to stress that I did not make the decision to remove `.watch()` lightly.

**Comment by fatoldsun00** [comment]
Hi nathan, thank for your answer

> My stance on settings observers now is that that sort of thing should really be handled by the developer. Electron Settings’ role is to act as a settings manager, not a settings nanny. While useful in many respects, I’m of the opinion nowadays that libraries shouldn’t do more than they need to.

It makes sense, that's what I was thinking

**Comment by vanowm** [comment]
With this logic - _if it's developers job to notify other parts of the code about changes in the settings_ - why bother with this module at all, since the developer might as well write their own settings module...

At least emit an event when a setting was been changed...
