### ISSUE TITLE
Doesn't work with Electron 14

### ISSUE THREAD

**Issue by ChugunovRoman** [nathanbuchar/electron-settings#157]
Current version (`4.0.2`) of Electron-settings doesn't work with new version Electron. I use Electron `v14.1.1`
I got a error in render process:

![screenshot_2021-10-11T21:07:18](https://user-images.githubusercontent.com/20404541/136835231-452bdac7-1132-408b-853a-e5eca5d2228c.jpg)

**Comment by sarathkurup87** [comment]
same issue!!

**Comment by ramaralo** [comment]
For those still in `v.3.#`
we can workaround this by:

```javascript
const remote = require("@electron/remote");

settings.setPath(path.join(remote.app.getPath("userData"), "Settings"));
```

This will still point to the default file but because it's using a custom path, `electron-settings` won't try to use `remote` from the `electron` dependency.

**Comment by jediwade** [comment]
@ChugunovRoman I am assuming you are trying to use electron-settings in the Renderer (you should provide more information in your bug reports). If you want to use the newer versions of Electron and have access to higher level APIs like remote, you need to make use of the [context isolation](https://www.electronjs.org/docs/latest/tutorial/context-isolation) feature to create a limited API that can be called from the Renderer. You shouldn't try to get around the security changes Electron has implemented. Yes the context isolation is a pain, but it is in the app user's best interest of your app.
