### ISSUE TITLE
windows `operation not permitted, rename ...`

### ISSUE THREAD

**Issue by yujingxiacai** [nathanbuchar/electron-settings#169]
Recently, when I opened my electron-application and the program ran to store the local custom data logic, the following error was reported.( I used `electron-settings` to store)

` Error: EPERM: operation not permitted, rename 'C:\Users\yujingxiacai\AppData\Roaming\Electron\settings.json.2501025886' -> 'C:\Users\yujingxiacai\AppData\Roaming\Electron\settings.json'`

> - **Opreating System**:    Windows 10 pro（21H2）
> - **Electron Version**:  ^15.1.0
> - **electron-settings**:  ^4.0.2

**Comment by quanglam2807** [comment]
Similar to https://github.com/nathanbuchar/electron-settings/issues/159. I think the solution is to disable `atomicSave` on Windows
