### ISSUE TITLE
Remove Keypath Watchers

### ISSUE THREAD

**Issue by nathanbuchar** [nathanbuchar/electron-settings#18]
The keypath watcher functionality adds unnecessary weight and dependencies to the package. In an effort to streamline and simplify, keypath watchers will be removed or drastically simplified in 2.0.0. 

If you have any concerns, let me know!

**Comment by wmhilton** [comment]
What's the replacement / way to get equivalent functionality? I was about to report a bug in `.watch` but if you're removing it...

I guess the solution to both would be, how do I set up functions to listen to changes to the settings?

**Comment by nathanbuchar** [comment]
I still plan on having a `.observe` or `.watch` event, however the return value will not be a complicated object using `deep-diff`, instead I plan on just sending `event.oldValue` and `event.newValue`. This is how Atom's internal config manager works, and I'm taking queues from their work. Back when I created key path watchers, they didn't have watch functionality, to my knowledge

**Comment by wmhilton** [comment]
Oooh, I didn't see there was a 2.0 branch... oops. Humble suggestion, I've used [EventEmitter2](https://www.npmjs.com/package/eventemitter2) in the past, and it supports "subscribing" with wildcards and events with namespaces. Inside the settings module, changes could broadcast an event with the keypath name

    settings.emit('change.' + keyPath, newValue)

This conveniently doesn't interfere with the existing 'change', 'error', 'save', and 'create' events.

Users could use listen for those changes using the EventEmitter2 interface which handles
adding watchers and removing watchers (issue #21) and eliminates the need for your own
watcher code.

```
/* Imaginary settings structure:
{
  github: {
    username: 'string',
    repo: 'string'
  },
  recentlyOpenedFiles: [
    {
      filename: 'string',
      lastSaved: Number,
      metadata: null
    }
  ]
}
*/

// Listen for changes to the github settings
settings.on('change.github.*', () => {
  // do stuff
})

// Listen for changes to any 'lastSaved' setting
settings.on('change.**.lastSaved', () => {  })
```

Just to clarify the use case, I'm trying to treat `settings` as a single-source-of-truth store, and have the rest of the application (including my UI) react to it. (Similar to React or Redux I guess?)
