### ISSUE TITLE
Docs missing

### ISSUE THREAD

**Issue by Zalk0** [nathanbuchar/electron-settings#181]
Hey,

Did you check your generated docs on [electron-settings.js.org](https://electron-settings.js.org) after doing the release ?
It's an empty page...

**Comment by nathanbuchar** [comment]
Thanks for the flag. Fixed!

**Comment by Zalk0** [comment]
Nice for the commit, you just forgot to run the deploy for it after :laughing:

**Comment by nathanbuchar** [comment]
Huh. It's supposed to do that automatically. Been too long since I've touched GitHub pages. The whole pipeline is probably broken now I guess. In any event, I fired it manually. Available now: https://electron-settings.js.org/

**Comment by Zalk0** [comment]
Yeah, probably your upgrade into downgrade of TypeDoc broke something, I don't know.
Thanks for fixing it anyway
