### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by Sigmanor** [nathanbuchar/electron-settings#2]
Where can I read more information about how to use it? When I'm using example from the readme, I got this error:

`Uncaught TypeError: Cannot read property 'getPath' of undefined`

**Comment by nathanbuchar** [comment]
I suspect you're using a version of Electron that is [`v0.34.0`](http://electron.atom.io/docs/v0.34.0/api/app/) or older. `electron-settings` only supports v0.35.0 and up.

The problem likely comes from [line 76](https://github.com/nathanbuchar/electron-settings/blob/master/lib/settings.js#L76) where we use `app` to get the path to the user's appData directory.

In [`v0.35.0`](http://electron.atom.io/docs/v0.35.0/api/app/) and up, `app` is defined like the following:

```js
let app = require('electron').app;
```

This definition is not compatible with older version of Electron. Remember, Electron is still in beta, so the API is constantly changing, so you may run into this with other packages. I'll make a note on the README about the requirements.

Does this help?

**Comment by Sigmanor** [comment]
Aww yes... Im using old version v0.33.3 Now I'm trying build my app with latest v0.36.7 Thank you for the explanation!

**Comment by nathanbuchar** [comment]
Great! I've been working all day on rewriting `electron-settings`. Lots of great new features :)
