### ISSUE TITLE
Cannot assign handler for the create event

### ISSUE THREAD

**Issue by dzava** [nathanbuchar/electron-settings#20]
Catching the create event is not possible currently. The event is emitted when a new instance is created but the handler has to be assigned on that instance after it is created.

**Comment by nathanbuchar** [comment]
Yes, I noticed this when writing for v2. Being that the file is created when ElectronSettings is instantiated, it is impossible to tie into the event. Will likely be removed in v2, or perhaps I'll find some way to tie it in

Thanks for flagging!
