### ISSUE TITLE
Multiple calls to `settings.watch('foo')` overwrite callbacks

### ISSUE THREAD

**Issue by wmhilton** [nathanbuchar/electron-settings#21]
I have two files, both wanting to listen to changes in the 'foo' setting. However multiple "watch" calls with the same keypath overwrite each other.

```
settings.watch('foo', () => {                     // this one gets over written
  console.error('foo = ', settings.get('foo'))  
})
settings.watch('foo', () => {                     // by this one
  console.error('!foo = ', !settings.get('foo'))
})
```

Figured I might as well report it in case others noticed it, even though you are planning to drop `watch` entirely?

**Comment by nathanbuchar** [comment]
I discovered this just a few days when writing for v2.0 – this has been fixed and will be published along with the v2 release. I'll let you know when it's live!

Thanks!
