### ISSUE TITLE
Where can it be used

### ISSUE THREAD

**Issue by nickdima** [nathanbuchar/electron-settings#26]
Does it work both on main and renderer?

**Comment by nathanbuchar** [comment]
Yessir! Just remember that ElectronSettings should be treated as a singleton, which is to say that only one instance should exist. Once you instantiate it you will only want to maintain a single copy – you should not create a new ElectronSettings instance within every module. More than one instance means that the disparate caches become forked and you will likely suffer data loss or corruption. There's a method in v2 that will help prevent this, but v2 has not yet been released.

**Good**
```js
// settings.js

// Creates a single instance of ElectronSettings and exports it.

const ElectronSettings = require('electron-settings');

const settings = new ElectronSettings();

module.exports = settings;
```
```js
// main.js

// Loads in the single settings instance.

const settings = require('./settings');

settings.set('foo', 'bar');
```

**Bad**
```js
// main.js

const ElectronSettings = require('electron-settings');

const settings = new ElectronSettings();

settings.set('foo', 'bar');
```
```js
// other.js

const ElectronSettings = require('electron-settings');

const settings = new ElectronSettings();

settings.set('foo', 'baz');
```

Does this help?

**Comment by nickdima** [comment]
I have multiple windows that need to read the settings. I have created the `settings.js` file like in your example and I'm requiring it from both windows but the thing is that if I update a setting from one window when I read it in the other I don't get the updated value (unless I close and reopen this window).

**Comment by nathanbuchar** [comment]
Interesting, I'll take a look

**Comment by nickdima** [comment]
By looking at the code it seems that there's no way around it unless `.get()` would read directly from the disk, because of the separate contexts of each page. No?

**Comment by nathanbuchar** [comment]
v2 will be released sometime between now and the next few days and no longer employs debounced save requests, and instead is a promise-based system. This should solve the issue :)

**Async**
```js
settings.set('foo', 'bar').then(() => {
  // Settings written.
});
```

**Sync**
```js
settings.setSync('foo', 'baz');
```
