### ISSUE TITLE
Syntax error in docs/methods

### ISSUE THREAD

**Issue by thardes2** [nathanbuchar/electron-settings#31]
There is a syntax error in the docs/methods file for the observe-method:
```
settings.observe('foo' evt => {
  // => {
  //   oldValue: 'bar',
  //   newValue: 'qux'
  // }
});
....
const observer = settings.observe('foo' evt => {
  // => {
  //   oldValue: 'bar',
  //   newValue: 'qux'
  // }
});
```

It should be 
`settings.observe('foo', evt => {`
and
`const observer = settings.observe('foo', evt => {`

(the , is missing)

**Comment by nathanbuchar** [comment]
Whoopsie :) thanks for flagging I'll take care of this tonight
