### ISSUE TITLE
Getting error when try to save settings

### ISSUE THREAD

**Issue by el-davo** [nathanbuchar/electron-settings#33]
Hi

I keep getting this error when trying to save settings.

```
key-path-helpers.js?158b:31 Uncaught (in promise) ReferenceError: splitKeyPath is not defined(…)
```

```
let electronSettings = require('electron-settings');

electronSettings.set('ect', {
 bla: 'bla'
});
```

It seems to be happening at this location in key-path-helpers module

https://github.com/atom/key-path-helpers/blob/master/lib/key-path-helpers.js#L31

**Comment by nathanbuchar** [comment]
Super weird. Thanks for tagging, I will take a look at this as soon as possible

**Comment by nathanbuchar** [comment]
I'm running a test for this exact case and it's not failing. Here is the test:

```js
it('should set the value at the chosen key path with an object', done => {
  settings.set('ect', {
    bla: 'bla'
  }).then(() => {
    settings.get('ect').then(value => {
      expect(value).to.deep.equal({ bla: 'bla' });
      done();
    });
  });
});
```

So everything is working as expected. What version of electron-settings are you using? And can I see how you're using the code in context?

**Comment by thalesrodolfo** [comment]
I'm having the same problem :(

version:

> └── electron-settings@2.1.1  extraneous


import of electron-settings:

`const settings = require('electron-settings')`

calling the method to handle the saving:

`<button type="button" name="button" @click="testeConfig()">Salvar Config</button>`

the method:
```
testeConfig: function () {
  settings.set('name', {
    first: 'Cosmo',
    last: 'Kramer'
  }).then(() => {
    settings.get('name.first').then(val => {
      // => "Cosmo"
    })
  })
  console.log(settings.getSettingsFilePath())
}
```

console output:
```
key-path-helpers.js?158b:31 Uncaught (in promise) ReferenceError: splitKeyPath is not defined(…)
    setValueAtKeyPath                @ key-path-helpers.js?158b:31
    _readSettingsFile.then.obj       @ settings.js?4fbf:410
```

**Comment by nathanbuchar** [comment]
Thanks for your info and reproduction steps. I'll take a look as soon as I can and see if I can find the root of the problem

**Comment by nathanbuchar** [comment]
This is an issue regarding transpiling from ES6. Moving conversation to #38
