### ISSUE TITLE
Option to specify save location  

### ISSUE THREAD

**Issue by N0taN3rd** [nathanbuchar/electron-settings#35]
In version 1.1.1 the ability to choose the location and directory name of the settings file was configurable via ```configDirPath``` when creating the settings object. 
This ability was extremely helpful for development purposes and specifying application specific storage locations as well as  renaming from defaults.
Utility gained from having this option was crucial when choosing a setting manager for [WAIL](https://github.com/N0taN3rd/wail) as shown in this  [use case ](https://github.com/N0taN3rd/wail/blob/electron/src/settings/settings.js) .

Love the new features in  2.1.1 such as promise usage which make this settings manager even better and want to upgrade if  this was some how possible.
Keep up the good work.   :+1:

**Comment by nathanbuchar** [comment]
Yes I intend to add it back in using the `configure()` method :)

**Comment by nathanbuchar** [comment]
v2.2.0 has the option to configure the instance with `settingsDir` and `settingsFileName`.

I chose not to add these options to the documentation for now, however. But they're there if you need them

```js
settings.configure({

  // defaults to `app.getPath('data')`
  settingsDir: '/Users/Nathan/Desktop',

  // defaults to `"Settings"`
  settingsFileName: 'MySettings'
});
```

**Comment by N0taN3rd** [comment]
@nathanbuchar That is so awesome thank you!!
Once again thanks for creating electron-settings.
