### ISSUE TITLE
Reset defaults on specific settings?

### ISSUE THREAD

**Issue by stursby** [nathanbuchar/electron-settings#43]
Is it possible to reset only _some_ settings to defaults?

Say I have the following:

```javascript
settings.defaults({
  foo: true,
  person: {
    name: 'Charlie',
    active: false
  }
});
```

At some point I set `person.active` to `true`. But on App Quit, I'd like to reset `settings.person`, while keeping `settings.foo` the same. Is this possible?

I'm trying to reset _some_ settings back to defaults on App Quit, so if there's a better way of doing, please let me know!

**Comment by nathanbuchar** [comment]
Good question, I'm surprised this isn't a thing! I had to go back into my own method docs just to make sure. I think I had planned to add a `reset` method but I guess slipped my mind!

I'll add this to my to-do list :)

**Comment by stursby** [comment]
@nathanbuchar Ok! Yea, I was digging through all the methods to see if one fit the bill.

I think it would be great to be able to pass a String to `reset`, like so:

```javascript
settings.setSync('person.name', 'foobar');
settings.setSync('person.active', true);

settings.resetDefaults('person')
// person.name = 'Charlie'
// person.active = false

settings.resetDefaults('person.name');
// person.name = 'Charlie'
// person.active = true
```

Something along those lines?

**Comment by tonioloewald** [comment]
settings.defaults() should automatically write undefined settings, otherwise adding a new settings breaks existing users and the only solution is to wrap everything in get/set promises which is horrible.

settings.defaults should write to a defaults object which is consulted by any get which turns up empty-handed.

**Comment by nathanbuchar** [comment]
Electron-settings v3.0.0 released.

`defaults()` and the like were removed in an effort to simplify the project
