### ISSUE TITLE
If key is exist

### ISSUE THREAD

**Issue by Sigmanor** [nathanbuchar/electron-settings#5]
Is there any way to check if key is exist and if not then create it? Because if I using this 
```
let winWidth = parseInt(settings.get('size')[0]);
let winHeight = parseInt(settings.get('size')[1]);
```
To get this parameters from `settings.json`:
![screenshot](http://i.imgur.com/Ucyl5KP.png)

And if this parameter is not exist I get an error:
![screenshot](http://i.imgur.com/ikJGSua.png)

**Comment by nathanbuchar** [comment]
Adding an `.exists()` method might be a good idea. Take the following example implementation for example:

```js
// With .exists()
if (!settings.exists('foo')) {
  settings.set('foo', 'bar');
}

// Without
if (typeof settings.get('foo') === 'undefined') {
  settings.set('foo', 'bar');
}
```

Additionally, I can add an option to `.get` allowing you to create the item if it does not exist:

```js
let foo = settings.get('foo', {
  createIfNotExists: true,
  default: 'bar'
});
```

Or something like that.

Definitely something to think about for future releases. Thanks for the tip!

**Comment by thranur** [comment]
I also want a similar feature, but I usually go for something such as `getOrDefault(key, def)`, which is roughly equivalent to:

```
function getOrDefault(key, def) {
  var v = get(key);
  if (v == undefined) {
    set(key, def);
    return def;
  } else return v;
}
```

It's sometimes easier to read the code when the default value is right next to its usage.

Anyway, it would be nice to have something like that as part of the default API.

**Comment by nathanbuchar** [comment]
A `.has(keyPath)` method has been added in 2.0.0 (unreleased). Example usage below:

```js
// Given: { "foo": "bar" }

settings.has('foo'); // true
settings.has('snoo'); // false
```
