### ISSUE TITLE
Set all settings at once

### ISSUE THREAD

**Issue by k7sleeper** [nathanbuchar/electron-settings#50]
Calling `settings.get()` you get all settings.
Calling `settings.set(null, config)` throws an error.

What do I have to do to store all (possibly changed) config values?

**Comment by z2oh** [comment]
I implemented this [on a fork here](https://github.com/z2oh/electron-settings/commit/8de338fdedae3bbd16fa76eac303e3ce267c1113). If @nathanbuchar wants to take a look at it, I would be happy to format to fit his style better and then add tests and open a pull request.

Passing a falsey value for set isn't really the clearest functionality, but the hacky method I was using before (clearing the settings then changing the defaults to the settings that I wanted then calling applyDefaults then setting the defaults back to the real defaults) was much worse. Unless there is some critical functionality I am missing here that enables this, I think passing a falsey value (which includes the empty string) makes some sense. Perhaps passing '.' or '*' to set the base settings object would make sense as well?

**Comment by nathanbuchar** [comment]
Electron-settings v3.0.0 released; You can now do this with `setAll()` :)

**Comment by k7sleeper** [comment]
Thanks!
