### ISSUE TITLE
Calling defaults() should set the default setting for any settings that don't yet exist

### ISSUE THREAD

**Issue by NoahAndrews** [nathanbuchar/electron-settings#53]
Right now, if an application adds a new setting, I believe you would need to manually detect whether or not it exists, and then set its default. This should all be taken care of when you call `defaults()`.

**Comment by nathanbuchar** [comment]
Electron-settings v3.0.0 released.

`defaults()` and the like were removed in an effort to simplify the project. But `get(keyPath, defaultValue)` is now a thing!
