### ISSUE TITLE
Atomic Saving causes EPERM on Windows

### ISSUE THREAD

**Issue by McPo** [nathanbuchar/electron-settings#55]
Upon first launching an application several settings are saved. However on windows I regularly encounter the issue of settings not saving correctly, the following is printed in the logs.

```
EPERM: operation not permitted, rename 'C:\Users\IEUser\AppData\Roaming\SaltIM\Settings-tmp' -> 'C:\Users\IEUser\AppData\Roaming\SaltIM\Settings'
```

I can switch off atomic saving, however Im wondering whether the atomic saving option was added due to a real occurring issue or was it added out of caution? (If so, is there a specific use case I should be testing for)

Im aware that this project is now deprecated and I had myself intended to replace it with a custom implementation, as my requirements have become more apparent. However I figured Id at least document this issue.

**Comment by nathanbuchar** [comment]
Can't remember what originally gave me the idea—I think it was from a PR to add functionality and I thought it was a good option so I added it in V2.

I wouldn't say the project is currently deprecated, I just have not been keeping up to date with it lately as my interests lie elsewhere at this time. I may open it back up and build a dramatically simplified V3 version, as one of my gripes with this project is its, I believe, unnecessary complexity.

**Comment by nathanbuchar** [comment]
Electron-settings v3.0.0 released; removed atomic saving option, as saving is no longer asynchronous.
