### ISSUE TITLE
Config path

### ISSUE THREAD

**Issue by Sigmanor** [nathanbuchar/electron-settings#6]
Using this code:
```
const ElectronSettings = require('electron-settings');
let settings = new ElectronSettings();
settings.set('foo', 'bar');
```
in main process create **settings.json** in `C:\Users\MyUsername\AppData\Roaming\MyAppName\electron-settings`. And when I use this code in renderer process file does not create there. Using: `console.log(settings.get('foo'));` I get result `bar` but I can not figure out where is the config file. Using `console.log(settings.getconfigfilepath());` throw error `Uncaught TypeError: settings.getconfigfilepath is not a function`

**Comment by nathanbuchar** [comment]
Use `settings.getConfigFilePath()`. Capitalization is important!

Does this help? Sorry for the delay, for some reason I wasn't notified of this issue being posted.

**Comment by nathanbuchar** [comment]
I just checked and I accidentally wrote the method wrong in the docs! Perhaps I should follow my own advice :-) I will fix this tonight
