### ISSUE TITLE
Sign Code error

### ISSUE THREAD

**Issue by hugosmarques** [nathanbuchar/electron-settings#68]
If i use the latest version of electron-settings 3.0.6 when i try to build using electon-builder with code signin the following error occur:

Error: Command failed: codesign --sign Developer ID Application: Areal-Media, Desenvolvimento de Software Lda (5BG5D3365B) --force --keychain /var/folders/cy/whzq6h3n4xbgh3x1grvn2kd80000gn/T/electron-builder-7H9fmK/0-1.keychain /Users/hugomarques/vsts-agent-mac/_work/3/s/dist/mac/UAUBook.app/Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework
/Users/hugomarques/vsts-agent-mac/_work/3/s/dist/mac/UAUBook.app/Contents/Resources/app.asar.unpacked/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework: bundle format unrecognized, invalid, or unsuitable

If i use the version 2.2.4 i don't get any error... WHY?

**Comment by nathanbuchar** [comment]
Hi @hugosmarques,

v3.0, being a major release, contains breaking changes from previous versions. Have you made all appropriate changes to your code to upgrade from v2 to v3? Or have you just installed the new version of electron-settings without making any modifications?

**Comment by hugosmarques** [comment]
a made the necessary modifications

2017-03-30 17:44 GMT+01:00 Nathan Buchar <notifications@github.com>:

**Comment by nathanbuchar** [comment]
Try [this](http://stackoverflow.com/questions/38948926/electron-builder-code-signing-bundle-format-unrecognized-invalid-or-unsuitabl#39009450).

Electron-settings v3 requires `electron`, not the deprecated `electron-prebuilt`
