### ISSUE TITLE
Use Array of JSON object to set() or setAll()

### ISSUE THREAD

**Issue by iamazik** [nathanbuchar/electron-settings#74]
Is there any way to use the array of JSON object to the `setAll()` method like the following?

```
{
  "backup": [
    {
      "id": 1,
      "name": "John Doe"
    },
    {
      "id": 2,
      "name": "Jane Doe"
    }
  ]
}
```

**Comment by nathanbuchar** [comment]
Hi @iamazik,

I'm afraid I don't understand. Are you having trouble performing the following operation?

```js
setting.setAll({
  "backup": [
    {
      "id": 1,
      "name": "John Doe"
    },
    {
      "id": 2,
      "name": "Jane Doe"
    }
  ]
});
```

**Comment by iamazik** [comment]
Thanks @nathanbuchar , I was just curious to know if there is a way to store the data in the array of JSON object? What I really meant is I want to store the array of JSON object using the `set()` method.

**Comment by nathanbuchar** [comment]
Oh, like modifying the array stored under in `"backup"`?

I'm afraid that's not possible. There's no way to access those properties directly using object dot notation as they are in an array. You will need to `get()` the value at `"backup"`, make the necessary modifications to the array, then set the value of `"backup"` to the updated array. Like so:

```js
const backup = settings.get('backup');

backup[0].name = "Nate Doe";

settings.set('backup', backup);
```

**Comment by iamazik** [comment]
Okay, Thanks @nathanbuchar

**Comment by nathanbuchar** [comment]
Let me know if you have any other questions!
