### ISSUE TITLE
Using watch() from renderer process

### ISSUE THREAD

**Issue by Dexwell** [nathanbuchar/electron-settings#75]
Thanks for the nice module. According to the [wiki](https://github.com/nathanbuchar/electron-settings/wiki/FAQs#can-i-use-electron-settings-in-both-the-main-and-renderer-processes), electron-settings can be used in the renderer process. Is this true for `watch()` as well?

I'm using the following code. The console doesn't log anything when I set a new `my-value` from the main process. Am I doing anything wrong?

```html
<script type="text/javascript">
	
    const settings = require('electron-settings');
    settings.watch('my-value', (newValue, oldValue) => {
        console.log(newValue);
    });

</script>

**Comment by nathanbuchar** [comment]
Hmm, must have something to do with creating the watcher in the renderer process, and setting the value in the main process. Perhaps the two instances are disjointed, because `settings.watch()` [passes tests for both processes](https://github.com/nathanbuchar/electron-settings/blob/master/tests/settings.js#L188).

I can't look at this now, but I will when I get home! Thanks for flagging

**Comment by nathanbuchar** [comment]
Confirmed I can reproduce this

**Comment by nathanbuchar** [comment]
Ah, the problem is that the internal `_watchSettings()` method is not being called unless a `_writeSettings()` is called, meaning that if you don't do a `set()` or `delete()` in the renderer process the FS Watcher will never be triggered.

I will fix this, thanks for flagging :-)

**Comment by nathanbuchar** [comment]
If you install `3.0.11` this issue should be fixed ✨

**Comment by Dexwell** [comment]
It works; fantastic 🙌🏼

**Comment by Dexwell** [comment]
Hey, not sure if this is related, but I may have found a bug. I think I can reproduce it like this: if the app has been inactive for a few minutes and I then set a new value which is being watched, I get the following error:

<img width="983" alt="screen shot 2017-04-04 at 20 12 09" src="https://cloud.githubusercontent.com/assets/521176/24672027/bccea022-1973-11e7-8cb7-cd3aa48c007c.png">

**Comment by nathanbuchar** [comment]
This error is coming from a settings file that is somehow not valid JSON. Can you inspect `/Users/You/Application\ Support/YourApp/Settings` and tell me if the file is malformed?

**Comment by Dexwell** [comment]
Yeah I did that and everything looks good. But `JSON.parse` does not seem to agree 🤔

<img width="522" alt="screen shot 2017-04-04 at 20 36 35" src="https://cloud.githubusercontent.com/assets/521176/24672903/a34fa33c-1976-11e7-8355-98ae3ef84997.png">

**Comment by nathanbuchar** [comment]
Well the problem there is that the object is not a string. Can't run `JSON.parse` on an object! Would it be too much trouble to delete the settings file (`rm /Users/Doney/Application\ Support/YourApp/Settings`) and see if that fixes it? If not, it likely may have something to do with my implementation using [jsonfile](https://www.npmjs.com/package/jsonfile) directly instead of using fs-extra as a middleman

**Comment by Dexwell** [comment]
Woops, haha. I deleted the Settings file and after retracing the same steps, rather than a `JSON.parse` error the Settings file is now emptied instead. Only `{}` remains.

**Comment by nathanbuchar** [comment]
Are `theme` and `remember-email` being set?

**Comment by Dexwell** [comment]
At startup the defaults for these settings are set if they don't exist yet. I wait a few minutes with the app inactive, and then only change (`set`) `remember-email`. Both are removed from the Settings file. When trying to set again after the removal I get the SyntaxError again.

**Comment by nathanbuchar** [comment]
This is a test script I'm running based on what you've described and I'm not running into issues:

```js
const settings = require('electron-settings');

settings.setAll({ foo: 'bar' });

settings.watch('foo', newValue => {
  console.log(`foo changed to: "${newValue}"`);
});

setTimeout(() => {
  settings.set('foo', 'new');
}, 1000 * 60 * 5);
```

Which after five minutes logs: `foo changed to: "new"`. 

Which version of electron-settings are you using, just I can be super sure?

**Comment by Dexwell** [comment]
I'm using electron-settings 3.0.13. 

Note that:
- Settings are being watched in both the main and renderer processes
- The above test script doesn't take into account that the app loses focus during the waiting period

(PS: The documentation on the wiki is a bit broken at the `setAll()` part; it's included in the code block for `set()`)

**Comment by nathanbuchar** [comment]
This is truly baffling. One thing electron-settings does, is if it cannot read the JSON file for whatever reason (invalid permissions, invalid JSON), it then attempts to write the file with an empty object, so that would explain the empty object you're seeing. There's something going wrong with parsing the JSON.

Is it possible that there are invisible artifacts in the strings you are `set`ing?

**Comment by Dexwell** [comment]
Haha, it is. The settings are only ever set by one of these: 

```javascript
settings.set('theme.sidebar', 'light');
settings.set('theme.sidebar', 'dark');
settings.set('remember-email', true);
settings.set('remember-email', false);
```

**Comment by nathanbuchar** [comment]
Would it be possible to share your code privately with me? I'd really like to get to the bottom of this.

**Comment by Dexwell** [comment]
Sure, I assume just the excerpts that deal with the settings? Would you like me to email you? I'm having trouble with consistently reproducing the issue myself.

**Comment by nathanbuchar** [comment]
My gut tells me race condition, but there's no way that's possible. Everything is sync!

[Email will work](mailto:hello@nathanbuchar.com), but if you have dropbox, you can share the whole project .zip there a bit easier. If the contents are too sensitive then just the files related to settings will work. Really appreciate it

**Comment by nathanbuchar** [comment]
Aha! I know what's going on. Both the main and renderer processes may be trying to access the file at the same time. The main and renderer process run on different threads, so this is possible.

I ran 10000 `set`s each on both the main and renderer processes at the same time, and sure enough I was getting `JSON.parse` errors as well as `{}`.

Wondering what a resolution for this could be…

**Comment by nathanbuchar** [comment]
Moved here: #81
