### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by florian** [nathanbuchar/electron-settings#8]
Are there any plans to add something like default settings? I'd guess that pretty much every app that has settings would need this.

It should work something like this: When initializing electron-settings (`new ElectronSettings`) an object with default settings can be passed. If there's no settings file so far, the default settings will be set. And there could be helper methods like resetting the settings to the default settings.

**Comment by cH40z-Lord** [comment]
It's now super trivial with the new `create` event to implement default settings. Actually it was the reason why I contributed it since I was facing the very same problem :)

Just add a new event handler for the `create` event and then set the values you need.

**Comment by nathanbuchar** [comment]
Looks like you might have missed my comment on one of your PRs—I asked if you'd like to add your name to the contributors in the `package.json` and `README`; I was waiting until then to push a new version. See [here](https://github.com/nathanbuchar/electron-settings/pull/15#issuecomment-231607245)

And as far as "defaults" implementation, I was picturing something along the lines of

```js
const settings = new ElectronSettings({
  defaults: {
    foo: 'bar'
  }
});
```

Just haven't gotten around to it. In the meantime, the `create` event that @cH40z-Lord contributed should suffice. Here's an example:

```js
const settings = new ElectronSettings();

// The settings file did not exist and was created
settings.on('create', () => {

  // Set defaults
  settings.set({
    foo: 'bar'
  });
});
```

**Comment by florian** [comment]
> Just haven't gotten around to it. In the meantime, the create event that @cH40z-Lord contributed should suffice.

It's nice, but I agree that there should also be a way to explicitly declare default settings. For example if I update my app and change the default settings and a user never changed a setting (i.e. they have the default settings), I might want him to get the updated default settings. This wouldn't work with the event and would require extra logic.

**Comment by nathanbuchar** [comment]
In theory, this should be easy to implement. I'll see if I can add it in tonight :) Sorry I've been a bit slow

**Comment by florian** [comment]
No worries :)

I think the important thing about the implementation is that the default settings shouldn't be saved to disk. If I try to retrieve a setting, the library should first look if a value for that setting was written to disk. If not, it should be checked if there's a default setting available.

This way the library would always return the 'newest' default setting if they were updated.

**Comment by nathanbuchar** [comment]
I was just thinking of doing an Object.assign (and saving to disk). See examples below

***

#### Case 1: No config file exists

**main.js**
```js
const settings = new ElectronSettings({
  defaults: {
    foo: 'bar',
    snap: 'pop'
  }
});
```

**settings.json**
```json
{
  "foo": "bar",
  "snap": "pop"
}
```

#### Case 2: A config file already exists

**settings.json**
```json
{
  "snap": "crackle"
}
```

**main.js**
```js
const settings = new ElectronSettings({
  defaults: {
    foo: 'bar',
    snap: 'pop'
  }
});
```

**NEW settings.json**
```json
{
  "snap": "crackle",
  "foo": "bar"
}
```

Notice how `"snap"` was not altered because a value was already present

**Comment by nathanbuchar** [comment]
This is now supported in v2.

```js
const settings = require('electron-settings');


// Must configure instance before running a command that 
// interacts with the file system in order for defaults to be applied.
settings.configure({
  defaults: {
    foo: 'bar'
  }
});

settings.get('

```
