### ISSUE TITLE
Parallel processes can collide during fs calls, resulting in malformed data and/or thrown errors

### ISSUE THREAD

**Issue by nathanbuchar** [nathanbuchar/electron-settings#81]
The main and renderer process run in different threads, so it's possible for the main and renderer electron-settings instances to collide when accessing the file system if they attempt to read/write the file at the same time. It should be noted that this issue is not unique to any version of electron-settings, nor electron-settings itself—any framework that can run in both processes that interact with the same file on the filesystem can encounter this problem.

This results in `JSON.parse` errors or, if the user is lucky, electron-settings will spot malformed JSON and reset the settings to fail gracefully, resulting in loss of data.

**Possible solutions**
- ~~Save the settings to a cached object and manipulate that instead. Every `set` or `delete` issues a throttled request to save the file to disk, so as to make interaction with the file-system far less frequent and decrease likelihood of collisions.~~ Seems to make no difference && race conditions with FSWatchers
- Suggest using `require('electron').remote.require('electron-settings')` in the render process to use the main processes' electron-settings instance.
- Suggest using electron-settings in only one process, or sparingly in the other.
- Instead of throwing, just try to read the settings file again.
- Find a way to ensure that the electron-settings instance is shared between both processes.
- Find a way to check if the file is in use before attempting to access it.
- Use IPC in the renderer to ask the main process' instance to save the file

<img width="532" alt="screen shot 2017-04-04 at 8 05 01 pm" src="https://cloud.githubusercontent.com/assets/1815367/24688011/0a3d5350-1972-11e7-9d5a-729ff487af07.png">

**Comment by Dexwell** [comment]
Props for finding the cause of the issue! It seems that for the time being, using `require('electron').remote.require('electron-settings')` is the best solution in version 3.0.13?

**Comment by nathanbuchar** [comment]
Well this would be an issue with every version of electron-settings, and even with other similar frameworks like electron-config. But yes, requiring electron-settings via `remote` in the renderer process will certainly work.

But for a cleaner solution, I would recommend using electron-settings in only one process—namely the renderer process. From what [I've read](https://discuss.atom.io/t/electron-app-database-file-structure-code-structure/16491/7) trying to find an answer to "keep single module instance between both processes", it seems like the agreed upon technique for Electron is to keep most of the logic in the renderer process<sup>[1](https://discuss.atom.io/t/node-frameworks-how-they-do-they-apply-to-electron/20011)</sup>, and the main process should really only be used to launch your app and set up the necessary windows.

**Comment by Dexwell** [comment]
Gotcha. Some of my settings are toggled in the app's View menu, so I would have to send a message to the BrowserWindow if a setting is changed. I was trying to avoid this by using `watch()`, so I guess by using remote I have found my preferred way of doing this :)

**Comment by nathanbuchar** [comment]
> send a message to the BrowserWindow if a setting is changed

You may want to check out the [`ipc`](https://electron.atom.io/docs/api/ipc-main/) module. Inter-process communication is what it's built for! :)

**Comment by Dexwell** [comment]
I know :) But that's not as slick as watching settings from wherever they are changed imo.

**Comment by callodacity** [comment]
Until a solid solution comes up, another potential fix may be: 

You could use a module like [`is-electron-renderer`](https://github.com/jprichardson/is-electron-renderer) when exporting the module, and return an the main process's instance then?

Something along the lines of:

eg: `index.js`
```javascript
const Settings = require('./lib/settings');
const isRenderer = require('is-electron-renderer');

if (isRenderer) {
  module.exports = require('electron').remote.require('electron-settings');
} else {
  module.exports = new Settings();
}
```

**Comment by nathanbuchar** [comment]
Yes, I have tested this in the past, but I remember running into a niche issue; can't remember what it was though. I'm going to run some tests to see if I can discover it again. So far everything seems fine using:

```js
// electron-settings/index.js

const electron = require('electron');
const Settings = require('./lib/settings');

if (electron.app) {
  module.exports = new Settings();
} else {
  module.exports = electron.remote.require('electron-settings');
}
```

```js
// electron-settings/lib/settings.js
// ...

class Settings extends EventEmitter {

  constructor() {
    super();

    // To use as a metric to check if the electron-settings
    // instance across processes is the same.
    this.r = Math.random();

    // ...
```

```js
// demo/main.js

const { BrowserWindow } = require('electron');
const path = require('path');
const settings = require('electron-settings');

// `0.929737048761468` for example 
console.log(settings.r);

let win1 = new BrowserWindow();
win1.loadURL(path.join('file://', __dirname, 'index.html'));

let win2 = new BrowserWindow();
win2.loadURL(path.join('file://', __dirname, 'index.html'));
```

```js
// demo/window.js

const settings = require('electron-settings');

// Matches `0.929737048761468`
console.log(settings.r);
```

It appears everything is working as expected. Even if I never require electron-settings from the main process, the electron-settings instance in both renderer processes have the same `r` value. I've definitely tested this before and I definitely ran into some sort of error… I'll keep checking edge cases.

**Comment by nathanbuchar** [comment]
I think one of my main concerns would baking

```js
if (electron.app) {
  module.exports = new Settings();
} else {
  module.exports = electron.remote.require('electron-settings');
}
```

into electron-settings itself. Yes, I want to ensure the same instance is used for each process, but this seems to me to be a bit of a hacky solution and might have unexpected consequences

**Comment by nathanbuchar** [comment]
Oh right… none of the renderer process tests pass. 🤔

**Comment by nathanbuchar** [comment]
Done that, but all the tests for the key path watchers in the renderer process are failing. I think that was the problem I was seeing before: weird `watch` behavior.

**Comment by nathanbuchar** [comment]
For some reason, when a key path watcher is defined within a renderer process, it's callback has the global context, and not the context of the SettingsObserver. This makes no sense.

```js
// main.js

settings.watch('foo', function handler() {
  console.log(this);
  // => SettingsObserver{...}
});

settings.set('foo', 'bar');
```

```js
// window.js

settings.watch('foo', function handler() {
  console.log(this);
  // => global (What?!?!)
});
```

**Comment by callodacity** [comment]
That does indeed make no sense at all!

You explicitly bind it to the Observer [here](https://github.com/nathanbuchar/electron-settings/blob/master/lib/settings-observer.js#L55). And you definitely use [call it with the binding too](https://github.com/nathanbuchar/electron-settings/blob/master/lib/settings-observer.js#L84).

Maybe this is a Chromium / electron bug with keeping context over `ipc`?

**Comment by callodacity** [comment]
I occasionally get these errors, but I can't seem to reproduce them well:

`Attempting to call a function in a renderer window that has been closed or released.`

Maybe passing it through the remote means it's not tracked by the renderer's garbage collector, and the passed object is getting cleaned up as well?

**Comment by nathanbuchar** [comment]
Hmm.. Oh, did you set a key path watcher (`.watch()`) in that renderer process? It could be that if you're requiring electron-settings via `remote`, when the renderer process is terminated the electron-settings instance isn't scrapped as well because it lives in the main process. However, if you've bound a key path watcher then if that setting changes, the electron-settings instance in the main process is trying to call the key path watcher handler but it no longer exists because the renderer window was closed, as the error states. Does that sound right?

**Comment by stavlocker** [comment]
> Suggest using require('electron').remote.require('electron-settings') in the render process to use the main processes' electron-settings instance.

Nice elegant solution, it's the one I liked the most. It's really effortless and wouldn't change existing code  drastically.
> Suggest using electron-settings in only one process, or sparingly in the other.

Another nice solution but it would require the developers using electron-settings to changes their code to match this solution.
> Instead of throwing, just try to read the settings file again.

Could cause unexpected behaviour if a process is trying to read the settings file over and over and another process is trying to do the same thing but keeps throwing error which would get it stuck in a loop/wait too long.
> Find a way to ensure that the electron-settings instance is shared between both processes.

Didn't quite understand this solution. Isn't this the same as the first solution?
> Find a way to check if the file is in use before attempting to access it.

Still, this could cause unexpected behaviour because people will implement this as `while(file is in use) read file again`
> Use IPC in the renderer to ask the main process' instance to save the file

Clean solution, but not as good as the first one as the first one is easier to use.

I think that the answer is the first solution - it's the cleanest and the simplest to use and the one that won't affect existing code by that much.

**Comment by semireg** [comment]
This issue really bit me. I sprinkled calls to settings throughout main and multiple renderer processes in a multi-document app. It took me half a day to refactor all calls to main, only. The solution for me was to leverage my existing state management pattern: redux, immutable.js, and electron-better-ipc. I wish the README of this project warned about concurrent access. It really would have saved me a headache... and bugs.

**Comment by kevinelliott** [comment]
I have also had a lot of pain here and don't have a great solution. In the renderer where do we define the `require('electron').remote.require('electron-settings')`? In `mounted()`? Or at the top with the rest of the imports?

**Comment by 2called-chaos** [comment]
Got also bitten and just wanted to share my solution (notably the watch solution). This is my first electron project so it might be a bad way of doing things (especially using synchronous ipc but I couldn't bother to promise everything) but you can let me know, maybe it helps someone :)

[class in main](https://github.com/2called-chaos/shadowplay-highlight-helper/blob/49232314850796be7c3525e820fa32b805e9665b/application/settings.js) // [init](https://github.com/2called-chaos/shadowplay-highlight-helper/blob/49232314850796be7c3525e820fa32b805e9665b/application.js#L38)
[class in windows/webcontents](https://github.com/2called-chaos/shadowplay-highlight-helper/blob/49232314850796be7c3525e820fa32b805e9665b/view/settings.js) // [example usage of get/watch](https://github.com/2called-chaos/shadowplay-highlight-helper/blob/49232314850796be7c3525e820fa32b805e9665b/view/client.js#L90-L91)

**Comment by nathanbuchar** [comment]
Closing this as it pertains to an older version of Electron Settings. A new major release (v4) of Electron Settings was just released! This new version should be much more reliable
