### ISSUE TITLE
Different Settings file path throws error

### ISSUE THREAD

**Issue by black-snow** [nathanbuchar/electron-settings#84]
> Uncaught Exception:
Error: ENOENT: no such file ...
...\Settings

```js
// main
import settings from 'electron-settings'

//...
app.setPath('userData', userDataPath + 'some addition');

//...
app.on('ready', function () {
  settings.get('whatver') // boom
}
```

I checked the path w/ `settings.file` and indeed it's not updated on `app.setPath`.

`fs.watch` has a lot of caveats - should we really rely on it? At least we must state this in the docs. Dunno if that's the origin my issue.

**Comment by nathanbuchar** [comment]
You will want to require electron-settings after the `app.setPath` directive or inside of the `app.on('ready')` callback, because as soon as electron-settings is required, it caches the userDataPath at that moment

**Comment by nathanbuchar** [comment]
In my apps, typically what I do is the following:

```js
// main.js

const { app } = require('electron');

// Additional setup like app.setPath

app.on('ready', () => {
  require('./lib/app');
});
```

```js
// lib/app.js

const settings = require('electron-settings');

// application code...
```

This setup ensures that application logic only follows after the app is ready.

**Comment by nathanbuchar** [comment]
At this time however, I will consider adding `settings.setPath` :) I'm on vacation this week but I'll plan to add this feature in this weekend

**Comment by black-snow** [comment]
Thanks for looking into this @nathanbuchar 

Should we be more clear about what happens when the path is changed in the API docs? I'd ask myself:

*Will existing settings be copied to the new location?*
*Which settings will be saved to the new location when I call `set()`? Everything, everything that's been loaded or just what I set?*
*Will `watch()` automagically watch the new file if I change the path?*

**Comment by nathanbuchar** [comment]
Good point, I'll make a note of this. For now, to answer it here:

1. Yes
2. Just what you set
3. Yes

**Comment by black-snow** [comment]
@nathanbuchar aren't 1. and 2. contradicting?

Maybe I should make it more clear:

1.) Will existing settings (i. e. file contents) be copied to the new location upon the call of `setPath()`?
-or-
2.) Will they be copied when I call `set()` and if yes what will be saved?

;)

**Comment by nathanbuchar** [comment]
Whoops! Read your first statement wrong

1. **No***
2. Just what you set
3. Yes
