### ISSUE TITLE
Not being able to run package

### ISSUE THREAD

**Issue by Kreshnik** [nathanbuchar/electron-settings#88]
Hi there,

I am trying to use the electron-settings package, however, I am receiving the following error when running my script;

```
This dependency was not found:

* fs in ./~/electron-settings/lib/settings.js, ./~/electron-settings/~/jsonfile/index.js and 3 others

To install it, you can run: npm install --save fs
```
I am running the following npm version `5.0.3`, any hints on what the cause might be?

**Comment by nathanbuchar** [comment]
I've seen this before using npm@5 and up, but with other packages. There's some weirdness and confusion surrounding the new `package-lock.json`. Try removing the `package-lock.json` file as well as the `node_modules` directory, then re-run `npm install` :)

```bash
rm package-lock.json
rm -rf node_modules
npm install
```

**Comment by Kreshnik** [comment]
Thanks @nathanbuchar it worked!
