### ISSUE TITLE
Windows - settings.has() throws error on first launch after install

### ISSUE THREAD

**Issue by CptMaumau** [nathanbuchar/electron-settings#90]
![image](https://user-images.githubusercontent.com/5366008/28506021-38d4bef4-7063-11e7-86d5-85879853ed44.png)

**Comment by nathanbuchar** [comment]
It would appear that the settings file is not being created or is inaccessible. It looks like the Settings file is located under `C:\Users\Administrator\…`. Does your current user have proper permissions to access files located under the Administrator's account?

**Comment by CptMaumau** [comment]
After looking at the Wiki I realized has was called too early, before the app is ready, and so I fixed it. You can close the issue. Thank you.

**Comment by nathanbuchar** [comment]
Great! Let me know if you have any other issues :)
