### ISSUE TITLE
Add setElectron to the API

### ISSUE THREAD

**Issue by kontrollanten** [nathanbuchar/electron-settings#94]
I'm implementing e2e tests with Spectron and would like to clear all my settings before each test. When running Spectron the electron instance isn't available via `require('electron')` from Spectron, why it isn't possible to run

```
beforeEach(function() {
  const app = new Application({...});
  const settings = require('electron-settings');
  settings.deleteAll();
});
```

Would it be possible to add something like `setElectron` to the API? Then it would be:
```
beforeEach(function() {
  const app = new Application({...});
  const settings = require('electron-settings');
  settings.setElectron(app.electron);
  settings.deleteAll();
});
```

I'm pretty new to Electron and I'm not sure that this is the right approach to solve my problem. But if you agree I'm happy to make a PR.

**Comment by nathanbuchar** [comment]
Why not just move the electron-settings require outside of the `beforeEach` directive?

```js
const settings = require('electron-settings');

beforeEach(() => {
  // ...
  settings.deletAll();
});
```

**Comment by kontrollanten** [comment]
Then I get the following error
```
TypeError: Cannot read property 'app' of undefined
    at Object.<anonymous> (.../node_modules/electron-settings/lib/settings.js:26:44)
```

Which comes from

```
const app = electron.app || electron.remote.app;
```

**Comment by hql287** [comment]
I'm also encountering this issue!

**Comment by nathanbuchar** [comment]
Closing this as it pertains to an older version of Electron Settings. A new major release (v4) of Electron Settings was just released! Electron Settings v4 does have support to define a custom electron instance via `configure()`.
