### ISSUE TITLE
QUESTION: Setting file location via setPath()

### ISSUE THREAD

**Issue by LorneCurrie** [nathanbuchar/electron-settings#95]
Hi there.

In your documentation, you mention we should not use `setPath()` to change the location of the `Setting` file, as this may have undesirable effects.  Could I change this in the case that I want the settings to be global to all users?  I am not worried about individual users have their own setting for the app.  I need the app to act and have the same setting for all user of a machine.

**Comment by nathanbuchar** [comment]
Hmm, in theory you could, but I think that depends on whether or not Electron has access to the root directory. You'll need to run your Electron app as the admin account, or give it admin privileges

**Comment by nathanbuchar** [comment]
Closing as it is not an issue, but feel free to continue the conversation here :)

**Comment by LorneCurrie** [comment]
Out of curiosity, what were the issues you picked up when testing with different Paths?

**Comment by nathanbuchar** [comment]
I didn't run into any errors per se, that disclaimer is really there for people who don't really know what they're doing, as it's kind of a low-level setting. If I recall, that verbiage was used in the Electron docs, but it looks like it may have been removed or I'm remembering incorrectly.

Best not to change it if you don't know what it does, but in your case using a root directory seems fine :)

**Comment by mike-zipit** [comment]
OK, here's the gotcha:  

* You must use setPath both in the main process and the renderer process
* You must use *_one_* instance of settings in the renderer.

So, my saga starts when I did the following in my main process:

    const settings = require('electron-settings');
    settings.clearPath().setPath(process.cwd() + '/Emulator.json');

And, throughout my renderer, I was using:

    const settings = require('electron').remote.require('electron-settings');

Turns out, each of these `require` statements re-import the module, resetting it back to the default path.

So, I have to move the settings in my renderer to (typescript):

    import {Settings} from "../../index";
    
    const settings : Settings = require('electron').remote.require('electron-settings');
    settings.clearPath().setPath(process.cwd() + '/Emulator.json');
    
    export default settings;

and changed all my imports to:

    import settings from "../../remoteSettings";
