### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by foreshadow** [nathanbuchar/electron-settings#97]
Hi, I am new to electron.
No matter in main.js or renderer.js
I call `settings.set('asd', 123)`
then `setting.get('asd')` will be nothing.
The demo's get-result is `undefined` too.

Will there be a system admin/permission problem? And how to solve this?
Win7, node 6.11

**Comment by foreshadow** [comment]
Now immediately `get` is working, but still not working `get` after the program exits.

**Comment by foreshadow** [comment]
it's working now, my fault.

**Comment by nathanbuchar** [comment]
:) glad you figured it out!
