### ISSUE TITLE
Calling Settings.has throws exception on windows when launching program for the first time after installation

### ISSUE THREAD

**Issue by MajPay** [nathanbuchar/electron-settings#99]
It seems the folder, where the settings should be stored does not exist when launching the program for the first time after installation on a windows machine.

I don't know, if the problem is related to electron-settings or the installation process of electron-packager.

I inspected the code of electron-settings and it seems, that the call to make sure the settings file exists, is present in has/get/set callstacks.

Did someone experience that issue too?

**Comment by MajPay** [comment]
Sorry, i found the issue. Instead of loading the Settings in the global scope of the main javascript file, you have to do it in the ready event of the electron app.

**Comment by nathanbuchar** [comment]
Yessir!

Glad you figured it out :-)
